neo4j_url: "******"

mysql:
  host: "******"
  port: "******"
  user: "******"
  password: "******"
  database: "******"

es:
  host:
    - "******"
    - "******"
    - "******"
    - "******"
  timeout:
    - "******"

mongo:
  - uri: "******"
  - db: "******"
  - col: "******"
redis:
  - uri: "******"

hbase:
  - # 配置
  - topic_num: "******"
  - # 默认配置
  - default_host: "******"
  - default_port: "******"
  - default_transport: "******"
  - default_compat: "******"
  - default_protocol: "******"

kafka:
  bootstrap_server:
    - "******"
    - "******"
    - "******"
  topic: "******"